# Funding

# This project does not accept donations or sponsorships.
#
# Why?
# - This is a passion project, not a business
# - No funding = no obligation to add features users "pay for"
# - Keeps the project independent and focused
# - Prevents feature creep driven by sponsor requests
#
# If you want to support this project:
# - Star the repository ⭐
# - Report bugs and suggest improvements
# - Contribute code or documentation
# - Share it with others who might find it useful
#
# Thank you for understanding!

# Uncomment and add links if you change your mind in the future:
# github: [yourusername]
# patreon: [username]
# ko_fi: [username]
# custom: ["https://example.com"]
